name: CI

on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install
      run: npm install
    - name: get data and build
      run: |
        node index.js
        node build.js
    - name: commit
      run: |
        git config --local user.email "pm.jamroz@gmail.com"
        git config --local user.name "ifrost"
        git commit -m "Update data.json" -a
        git checkout gh-pages
        git merge origin/master
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
